### ISSUE TITLE
Extract normalized matrix after batch correction

### ISSUE THREAD

**Issue by SharonWang** [drisso/zinbwave#12]
Dear All,

I am wondering if there is a way to extract normalized matrix after batch correction?

In addition, I tried with K=20, but it gave me the following error message and returned empty W:

Warning message:
In simpute.als(x, J, thresh, lambda, maxit, trace.it, warm.start,  :
  Convergence not achieved by 100 iterations

**Comment by SharonWang** [comment]
I figured out why W is empty as I thought K=2 is the default setting. But the problem comes the parameter ncores does not exist anymore...

**Comment by drisso** [comment]
Hi @SharonWang 

The normalized matrix can be extracted using the `zinbwave` function with `normalizedValues = TRUE`.

The message that you pasted above is not an error, but a warning and it's OK to ignore since it only applies to the initialization step. 

The fact that it returns an empty W is clearly not what should happen, but it's hard to see what's going on without a reproducible example.

Can you please paste here the code that you used for the analysis and the version of zinbwave that you're using?

**Comment by SharonWang** [comment]
Hi @drisso 

Thank you very much for your help.

Several other questions:
- I tried with the model with K=2 and K=20, but it seems that it gave me normalised matrix with different values as I would expect these should be more or less similar. (The range for K=2 is c(-4.61, 21.56), whereas the range for K=20 is c(-4.56, 37.67).

-  I included batch in the X matrix, K=2, it worked really well, very similar to normalization following batch correction, however, if I set K=20, I start to see strong batch effects again. It did not happen with normalization following by batch correction. Could you please see what happened? It is to do with the warning message?

- For the empty W issue, I didn't know why it happened but it was solved by close down R and restart it again.

Look forward to your reply.

**Comment by SharonWang** [comment]
In addition, I also tried extract K=2 normalised matrix and then do a PCA and take the top 20 PCs, similar to what happened with K=20, I see strong batch effects.

**Comment by drisso** [comment]
Can you be more specific in what you mean by "see strong batch effects?" Are these in the components of W other than the first 2?

Because it happens with PCA too, I'm inclined to think that it means that including the batch in X is not enough to capture all the batch effects, which are still present but not enough to influence the first two components and they show up only in higher order components.

Did I understand correctly? If so, I think that trying to capture batch effects in a different way (e.g., by using sva or RUV) could help.

**Comment by SharonWang** [comment]
Hi @drisso 

Thank you very much for your suggestions.

Sorry for not describing it clearly. 'Strong batch effects' means as it showed for the data before any batch correction (The raw data has strong batch effect). These were well corrected for K=2, but for K=20, these show in the first 2 components. 

The details of what I did was (all included batch in X matrix):

- K=2
  - plotted W: worked very well
  - extracted normalised matrix, then did a PCA, top 2 PCs similar to W, worked very well, but batch effect observed if consider all top 20 PCs
- K=20
  - plotted top 2 W components: batch effect observed as raw data
  - extracted normalised matrix, did a PCA, got results similar to K=2

As you suggested, I will try batch correction first then use ZINBwave after.
